"""Publish an immutable read model generated by the local API; never overwrite reviews.
Run with uv run python scripts/export_cloudflare.py. Generated data stays out of Git.
"""

import argparse
import json
import sqlite3
import tempfile
import uuid
from pathlib import Path
from fbcv_calendar.api import create_app, normalized
from fbcv_calendar.conflicts import detect_conflicts

parser = argparse.ArgumentParser()
parser.add_argument("--db", default="data/fbcv.sqlite3")
parser.add_argument("--season", default="2026")
parser.add_argument("--output", default="data/cloudflare-snapshot.sql")
args = parser.parse_args()
if not args.season.isdigit() or len(args.season) != 4:
    parser.error("La temporada debe tener 4 cifras")
# Work from a consistent SQLite backup even if the crawler refreshes the source.
copy_dir = tempfile.TemporaryDirectory(prefix="fbcv-cloudflare-")
source = Path(args.db).resolve()
copy_db = Path(copy_dir.name) / "source.sqlite3"
with sqlite3.connect(source.as_uri() + "?mode=ro", uri=True) as origin:
    with sqlite3.connect(copy_db) as destination:
        origin.backup(destination)
args.db = str(copy_db)
app = create_app(args.db, static_dir="data/no-static")
endpoints = {r.path: r.endpoint for r in app.routes if hasattr(r, "endpoint")}
clubs = endpoints["/api/clubs"](season=args.season, q="")
metadata = endpoints["/api/meta"](season=args.season)
if not clubs:
    parser.error("No hay clubes con calendarios para exportar")
snapshot = uuid.uuid4().hex
output = Path(args.output)
output.parent.mkdir(parents=True, exist_ok=True)
temp = output.with_name(output.name + "." + snapshot + ".tmp")


def quote(x):
    return "NULL" if x is None else "'" + str(x).replace("'", "''") + "'"


def payload(x):
    return json.dumps(x, ensure_ascii=False, separators=(",", ":"))


counts = {"clubs": len(clubs), "teams": 0, "conflicts": 0}
with (
    sqlite3.connect(Path(args.db).resolve().as_uri() + "?mode=ro", uri=True) as conn,
    temp.open("w") as f,
):
    conn.row_factory = sqlite3.Row

    def insert(table, values):
        statement = (
            "INSERT INTO "
            + table
            + " VALUES("
            + ",".join(quote(v) for v in values)
            + ");\n"
        )
        if len(statement.encode()) >= 100_000:
            raise ValueError(
                "Una fila supera el límite SQL de D1. No se publica esta extracción."
            )
        f.write(statement)

    insert("cf_snapshots", [snapshot, args.season, payload(metadata)])
    for n, club in enumerate(clubs, 1):
        insert(
            "cf_clubs",
            [
                snapshot,
                club["id"],
                club["name"],
                normalized(club["name"]),
                club["team_count"],
            ],
        )
        teams = endpoints["/api/clubs/{club_id}/teams"](
            club_id=club["id"], season=args.season
        )
        for team in teams:
            insert("cf_teams", [snapshot, club["id"], team["id"], payload(team)])
            calendar = endpoints["/api/clubs/{club_id}/teams/{team_id}/calendar"](
                club_id=club["id"], team_id=team["id"], season=args.season
            )
            insert(
                "cf_calendars", [snapshot, club["id"], team["id"], payload(calendar)]
            )
        items, skipped = detect_conflicts(conn, args.season, club["id"])
        insert("cf_conflict_meta", [snapshot, club["id"], skipped])
        for item in items:
            insert("cf_conflicts", [snapshot, club["id"], item["id"], payload(item)])
        counts["teams"] += len(teams)
        counts["conflicts"] += len(items)
        if n % 20 == 0:
            print(f"Exportados {n}/{len(clubs)} clubes", flush=True)
    # Publishing the pointer last leaves a prior snapshot active on a partial import.
    f.write(
        "INSERT INTO cf_active_snapshot VALUES("
        + ",".join(quote(v) for v in [args.season, snapshot])
        + ") ON CONFLICT(season) DO UPDATE SET snapshot_id=excluded.snapshot_id;\n"
    )
temp.replace(output)
copy_dir.cleanup()
print(json.dumps({"snapshot": snapshot, "output": str(output), **counts}), flush=True)
